resolver: snapshot.yaml
packages:
- servant-multipart-client
- servant-multipart
- servant-multipart-api
extra-deps:
#- git: https://github.com/mwotton/roboservant
#  commit: 3deefd61396f33270a747643aea713f50315ce7c
 #- git: https://github.com/jfischoff/postgres-options
  #commit: 45bafb2092bc7a7b3c561608295294d562313dd3
- git: https://github.com/jfischoff/tmp-postgres
  commit: 593e3ebcb7643afd6095f6269de3552d01c7ff40
- postgres-options-0.2.0.0@sha256:5e2d6408ed3943f9a056b58106186397b9aa1424c56f1f26668305ce8ea2838f,1604
- git: https://github.com/MonadicSystems/servant-htmx
  commit: db30209295bd0446d316cae5880fb7a6b36a733e
- servant-server-0.20
- servant-0.20
- lucid-xstatic-0.1.1
- xstatic-0.2.0
- git: https://github.com/haskell-servant/servant-lucid
  commit: 28faa2b57ab01b105c35f30908630900f55b5576
- servant-xstatic-0.1.0
- git:  git@github.com:lambdamechanic/dutchelm
  commit: c35d25e939aee2ea6e8a28daa0ca22dc1159d51c
- git: git@github.com:lambdamechanic/quickjs-hs
  commit: 22048e08b91bab5eaf61255c22d195579813278f
  # annoyingly, this appears to be behind the github.
- git: https://github.com/nh2/call-haskell-from-anything
  commit: e7c4648bd38d3e61970b916f4760f77e744629b3
  # - call-haskell-from-anything-1.1.0.0
- posix-escape-0.1
- git: https://github.com/lambdamechanic/hxt
  commit: d063d93d050367dba7617fa5b937ed609c446671
  subdir: hxt-xpath
- openai-hs-0.3.0.1
- openai-servant-0.3.0.1
- servant-client-0.20
- servant-client-core-0.20
- servant-docs-0.13
- servant-foreign-0.16
# - servant-multipart
